function [outputcarbon,outputSO2,outputNOx] = importcarbonuni(mon)
%% importing carbon intensity data
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\harry\Documents\work\4 year\usmonthlyaveragehourlyemissionfactorsforerctegridsubregion.xlsm
%    Worksheet: usmonthlyaveragehourlyemissionf
%
% Auto-generated by MATLAB on 21-Nov-2018 11:36:14

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 14);

% Specify sheet and range
opts.Sheet = "usmonthlyaveragehourlyemissionf";
opts.DataRange = "A3:N303";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "CO2lbsMWh", "CO2lbsMWh1", "CO2lbsMWh2", "CO2lbsMWh3", "SO2lbsMWh", "SO2lbsMWh1", "SO2lbsMWh2", "SO2lbsMWh3", "NOxlbsMWh", "NOxlbsMWh1", "NOxlbsMWh2", "NOxlbsMWh3"];
opts.VariableTypes = ["categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
uscarbon = readtable("J:\dis\usmonthlyaveragehourlyemissionfactorsforerctegridsubregion.xlsm", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%mon = 'January';
carbonmonth = table2array(uscarbon(:,1)); 
carbonhour= table2array(uscarbon(:,2));     % 24 hour resolution
averagecarbon = table2array(uscarbon(:,4)); % lbs/Mwh
averageSO2 = table2array(uscarbon(:,8));    % lbs/Mwh
averageNOx = table2array(uscarbon(:,12));   % lbs/Mwh

avCkg = averagecarbon * 0.453592 /1000;  % convert to Kg/Kwh
avSO2kg = averageSO2 * 0.453592 / 1000; 
avNOxkg = averageNOx * 0.453592 / 1000;

inds = find(carbonmonth==mon);
outputcarbon = avCkg(inds(2:end)); 
outputSO2 = avSO2kg(inds(2:end));
outputNOx = avNOxkg(inds(2:end));



end

