function out = inonedayuni()

%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\harry\Documents\work\4 year\1dayprice.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/02/07 15:09:22

%% Initialize variables.
filename = 'J:\dis\1dayprice.csv';
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: datetimes (%{dd/MM/yyyy hh:mm:ss a}D)
%	column2: double (%f)
%   column3: categorical (%C)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{dd/MM/yyyy hh:mm:ss a}D%f%C%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
dayprice = table(dataArray{1:end-1}, 'VariableNames', {'Date','Price','Zone'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% dayprice.Date=datenum(dayprice.Date);

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;



pricedateone = table2array(dayprice(:,1));
pricevone = table2array(dayprice(:,2));   % $/Mwh
pricezoneone = table2array(dayprice(:,3));

zoneone = 'LZ_CPS';

zoneinds = find(pricezoneone== zoneone);
%% getting the data for only the correct zone
pricevzoone = pricevone(zoneinds);       
pricedatezoone = pricedateone(zoneinds);
priceadjustedone = pricevzoone/1000; % convert to $/Kwh
out = priceadjustedone(2:end);

end
