function dataportexport = newdetoctuni()
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\harry\Documents\work\4 year\dataport-export.xlsx
%    Worksheet: dataport-export
%
% Auto-generated by MATLAB on 05-Nov-2018 19:58:11

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "dataport-export";
opts.DataRange = "A2:D1048576";

% Specify column names and types
opts.VariableNames = ["localminute", "dataid", "use", "gen"];
opts.VariableTypes = ["datetime", "double", "double", "double"];

% Import the data
dataportexport = readtable("J:\dis\dataport-export.xlsx", opts, "UseExcel", false);


end